# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REFRESH STREAMING TABLE cust_bronze_addcols
# MAGIC COMMENT "Bronze table using schemaEvolutionMode=addNewColumns"
# MAGIC AS
# MAGIC SELECT
# MAGIC   CustomerID,
# MAGIC   Name,
# MAGIC   Email,
# MAGIC   PhoneNumber,
# MAGIC   City,
# MAGIC   signupDate,
# MAGIC   CreditScore,
# MAGIC   current_timestamp() AS _ingest_ts,
# MAGIC   _metadata.file_path  AS _source_file
# MAGIC FROM cloud_files(
# MAGIC   '/Volumes/workspace/damg7370/datastore/schema_drift/addnew_input',
# MAGIC   'json',
# MAGIC   map(
# MAGIC     'schemaLocation',      '/Volumes/workspace/damg7370/datastore/schema_drift/addnew_schema',
# MAGIC     'schemaEvolutionMode', 'addNewColumns',
# MAGIC     'multiLine',           'true'
# MAGIC   )
# MAGIC );
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE OR REFRESH STREAMING TABLE cust_silver_addcols
# MAGIC COMMENT "Silver table for addNewColumns; cast datatypes and apply basic quality rules"
# MAGIC AS
# MAGIC SELECT
# MAGIC   CustomerID,
# MAGIC   Name,
# MAGIC   Email,
# MAGIC   PhoneNumber,
# MAGIC   City,
# MAGIC   TO_DATE(signupDate)              AS signupDate,      -- string → date
# MAGIC   CAST(CreditScore AS DOUBLE)      AS CreditScore,     -- string → double
# MAGIC   _ingest_ts,
# MAGIC   _source_file
# MAGIC FROM STREAM(LIVE.cust_bronze_addcols)
# MAGIC WHERE CustomerID IS NOT NULL;
# MAGIC
